networks:
  littlechefrecipes:

services:
  eureka-registry:
    restart: always
    networks:
      - littlechefrecipes
    ports:
      - 15000:8761
    container_name: LittleChefsEureka
    image: steeltoeoss/eureka-server

  littlechef-gateway:
    container_name: littlechef-gateway
    build:
      context: ./apigateway-ocelot-dotnet8
      dockerfile: Dockerfile
    image: gateway:1
    restart: always
    hostname: littlechef-gateway
    ports:
      - 15010:8080
    networks:
      - littlechefrecipes
    depends_on:
      - eureka-registry  

  # Databases

  littlechef-mongo:
    restart: always
    networks:
      - littlechefrecipes
    ports:
      - 15004:27017
    container_name: LittleChefsMongo
    image: mongo

  littlechef-redisstack:
    restart: always
    networks:
      - littlechefrecipes
    ports:
      - 15006:6379
      - 15007:8001
    container_name: LittleChefsRedisStack
    image: redis/redis-stack:latest

  littlechef-sql:
    restart: always
    networks:
      - littlechefrecipes
    ports:
      - 15008:3306
    container_name: LittleChefsSQL
    environment:
      - MYSQL_ROOT_PASSWORD=abc123!!!
      - MYSQL_DATABASE=orders
    image: mysql:latest

  # Services Initialization 

  littlechef-userservice:
    depends_on:
      - eureka-registry
    restart: always
    networks:
      - littlechefrecipes
    build: ./Backend/UserAPI
    deploy:
      replicas: 5

  littlechef-recipeservice:
    depends_on:
      - eureka-registry
    restart: always
    networks:
      - littlechefrecipes
    build: ./Backend/RecipeAPI
    environment:
      - PYTHONUNBUFFERED=0
    deploy:
      replicas: 5

  # littlechef-basketservice:
  #   depends_on:
  #    - eureka-registry
  #   restart: always
  #   networks:
  #     - littlechefrecipes
  #   ports:
  #     - "15040-15049:15013"
  #   build: ./Backend/BasketService
  #   deploy:
  #      replicas: 5
  
  # littlechef-orderservice:
  #   depends_on:
  #    - eureka-registry
  #   restart: always
  #   networks:
  #     - littlechefrecipes
  #   ports:
  #     - "15050-15059:15014"
  #   build: ./Backend/OrderService
  #   deploy:
  #      replicas: 5