networks:
  littlechefrecipes:

services:
  LittleChefsEureka:
    restart: always
    networks:
      - littlechefrecipes
    ports:
      - 15000:8761
    container_name: LittleChefsEureka
    hostname: LittleChefsEureka
    image: steeltoeoss/eureka-server

  littlechef-gateway:
    container_name: littlechef-gateway
    build:
      context: ./Backend/apigateway-ocelot-dotnet8
      dockerfile: Dockerfile
    image: gateway:1
    restart: always
    hostname: littlechef-gateway
    ports:
      - 15010:15010
    networks:
      - littlechefrecipes
    depends_on:
      - LittleChefsEureka 

  # Databases

  littlechef-mongo:
    restart: always
    networks:
      - littlechefrecipes
    ports:
      - 15004:27017
    container_name: LittleChefsMongo
    image: mongo

  littlechef-redisstack:
    restart: always
    networks:
      - littlechefrecipes
    ports:
      - 15006:6379
      - 15007:8001
    container_name: LittleChefsRedisStack
    image: redis/redis-stack:latest

  littlechef-sql:
    restart: always
    networks:
      - littlechefrecipes
    ports:
      - 15008:3306
    container_name: LittleChefsSQL
    environment:
      - MYSQL_ROOT_PASSWORD=abc123!!!
      - MYSQL_DATABASE=orders
    image: mysql:latest

  # Services Initialization 

  littlechef-userservice:
    depends_on:
      - LittleChefsEureka
    restart: always
    networks:
      - littlechefrecipes
    build: ./Backend/UserAPI
    deploy:
      replicas: 5

  littlechef-recipeservice:
    depends_on:
      - LittleChefsEureka
    restart: always
    networks:
      - littlechefrecipes
    build: ./Backend/RecipeAPI
    environment:
      - PYTHONUNBUFFERED=0
    deploy:
      replicas: 5

  littlechef-bascket-api:
    depends_on:
      - LittleChefsEureka
      - littlechef-gateway
      - littlechef-redisstack
    restart: always
    networks:
      - littlechefrecipes
    build: ./Backend/BascketAPI
    environment:
      - EUREKA_HOST=LittleChefsEureka
  
  littlechef-orderservice:
    depends_on:
      - LittleChefsEureka
      - littlechef-gateway
      - littlechef-sql
    restart: always
    networks:
      - littlechefrecipes
    build: ./Backend/OrderService